
package atj.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Attachment", targetNamespace = "http://ws.atj/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Attachment {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://ws.atj/", className = "atj.ws.DownloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://ws.atj/", className = "atj.ws.DownloadFileResponse")
    @Action(input = "http://ws.atj/Attachment/downloadFileRequest", output = "http://ws.atj/Attachment/downloadFileResponse")
    public byte[] downloadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://ws.atj/", className = "atj.ws.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://ws.atj/", className = "atj.ws.UploadFileResponse")
    @Action(input = "http://ws.atj/Attachment/uploadFileRequest", output = "http://ws.atj/Attachment/uploadFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://ws.atj/Attachment/uploadFile/Fault/IOException")
    })
    public void uploadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws IOException_Exception
    ;

}
