
package atj.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AttachmentService", targetNamespace = "http://ws.atj/", wsdlLocation = "http://localhost:8080/WebServiceAttachment/AttachmentService?wsdl")
public class AttachmentService
    extends Service
{

    private final static URL ATTACHMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATTACHMENTSERVICE_EXCEPTION;
    private final static QName ATTACHMENTSERVICE_QNAME = new QName("http://ws.atj/", "AttachmentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServiceAttachment/AttachmentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATTACHMENTSERVICE_WSDL_LOCATION = url;
        ATTACHMENTSERVICE_EXCEPTION = e;
    }

    public AttachmentService() {
        super(__getWsdlLocation(), ATTACHMENTSERVICE_QNAME);
    }

    public AttachmentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATTACHMENTSERVICE_QNAME, features);
    }

    public AttachmentService(URL wsdlLocation) {
        super(wsdlLocation, ATTACHMENTSERVICE_QNAME);
    }

    public AttachmentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATTACHMENTSERVICE_QNAME, features);
    }

    public AttachmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AttachmentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Attachment
     */
    @WebEndpoint(name = "AttachmentPort")
    public Attachment getAttachmentPort() {
        return super.getPort(new QName("http://ws.atj/", "AttachmentPort"), Attachment.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Attachment
     */
    @WebEndpoint(name = "AttachmentPort")
    public Attachment getAttachmentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.atj/", "AttachmentPort"), Attachment.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATTACHMENTSERVICE_EXCEPTION!= null) {
            throw ATTACHMENTSERVICE_EXCEPTION;
        }
        return ATTACHMENTSERVICE_WSDL_LOCATION;
    }

}
